name: linting-workflow
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install --save-dev htmlhint
      - name: Lint All CSS Files
        run: npx htmlhint "**/*.css"

      - name: Install StyleLint
        run: npm install --save-dev stylelint
      - name: Lint All CSS Files
        run: npx stylelint "**/*.css"